package com.skiwi.granadoespadatools.model.objects;

/**
 * @author Frank van Heeswijk
 */
public enum EffectType {
    SP_REGENERATION,
    ACCURACY,
    ATK_SPD_PERCENTAGE,
    CRITICAL,
    DEF_PENETRATION_RATE,
    FIRE_PENETRATION_RATE,
    ICE_PENETRATION_RATE,
    LIGHTNING_PENETRATION_RATE,
    MENTAL_PENETRATION_RATE,
    ATK_PERCENTAGE,
    AR,
    DR,
    DEMONS_PERCENTAGE,
    SKILL_EVASION_PERCENTAGE,
    INT,
    MAX_HP_PERCENTAGE,
    MONSTER_DAMAGE_PERCENTAGE,
    COMBAT_EXP_PERCENTAGE,
    STANCE_EXP_PERCENTAGE,
    ITEM_DROP_RATE_PERCENTAGE,
    IF_ENEMY_BELOW_50_DAMAGE_INCREASE_PERCENTAGE,
    DEF,
    RES,
    MAX_HP,
    MOVE_SPD_PERCENTAGE;
}
